# Generated by Django 5.1.4 on 2024-12-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesetting',
            name='image_location',
            field=models.CharField(choices=[('0', 'لا بوجد صورة'), ('1', 'اعلي اليمين'), ('2', 'اعلي اليسار')], default=0, max_length=25),
        ),
    ]
