# Generated by Django 5.1.4 on 2024-12-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificateTypes',
            new_name='CertificateType',
        ),
        migrations.CreateModel(
            name='CertificateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('has_image', models.BooleanField()),
                ('image_location', models.CharField(choices=[(1, 'اعلي اليمين'), (2, 'اعلي اليسار')], default=1, max_length=25)),
                ('certificate_content', models.TextField()),
                ('CertificateType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CertificateType', to='certificates.certificatetype')),
            ],
        ),
        migrations.DeleteModel(
            name='CertificateSettings',
        ),
    ]
