# Generated by Django 5.1.4 on 2024-12-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificatesetting_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='certificates.certificatetype'),
            preserve_default=False,
        ),
    ]
