# Generated by Django 5.1.4 on 2024-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_rename_certificatetypes_certificatetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesetting',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
