# Generated by Django 5.1.4 on 2024-12-16 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatetype_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='certificates.certificatetype'),
        ),
    ]
