# Generated by Django 5.1.4 on 2024-12-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programe',
            name='en_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='programe',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
