# Generated by Django 5.1.4 on 2024-12-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_programe_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programe',
            name='en_Name',
            field=models.CharField(default='prog', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programe',
            name='en_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programe',
            name='en_full_path_name',
            field=models.CharField(default='prog', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programe',
            name='url',
            field=models.CharField(default='prog', max_length=50),
            preserve_default=False,
        ),
    ]
